### ISSUE TITLE
agent is not defined

### ISSUE THREAD

**Issue by ctgraham** [bryklaus/glpc_related-entries#21]
Request of `/api/data?id=50` fails on:
https://github.com/bryklaus/glpc_related-entries/blob/8f9dca72e809ed7e2d2b6e930d96da36f16e2f77/app/src/routes/data.js#L31

With message:
```
ReferenceError: agent is not defined
    at /app/src/routes/data.js:31:4
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/app/node_modules/express/lib/router/index.js:175:3)
    at router (/app/node_modules/express/lib/router/index.js:47:12)
```

**Comment by ctgraham** [comment]
Perhaps this?
https://github.com/bryklaus/glpc_related-entries/blob/8f9dca72e809ed7e2d2b6e930d96da36f16e2f77/app/src/routes/data.js#L10-L13

**Comment by bryklaus** [comment]
That’s definitely it. I always have to uncomment those lines when I’ve tested the app on my home computer, so never encountered that error.On Sep 29, 2023, at 11:46, Clinton Graham ***@***.***> wrote:﻿
Perhaps this?
https://github.com/bryklaus/glpc_related-entries/blob/8f9dca72e809ed7e2d2b6e930d96da36f16e2f77/app/src/routes/data.js#L10-L13

**Comment by bryklaus** [comment]
I assume we can just comment out the “agent” line and it should work - or at least not produce that error anymore.On Sep 29, 2023, at 11:47, Bryan Klausmeyer ***@***.***> wrote:﻿That’s definitely it. I always have to uncomment those lines when I’ve tested the app on my home computer, so never encountered that error.On Sep 29, 2023, at 11:46, Clinton Graham ***@***.***> wrote:﻿
Perhaps this?
https://github.com/bryklaus/glpc_related-entries/blob/8f9dca72e809ed7e2d2b6e930d96da36f16e2f77/app/src/routes/data.js#L10-L13
